/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.microsoft.ui.pages;

public class CareerPage {
    public boolean someLibraryMethod() {
        return true;
    }
}
